import type { AnalysisResult, Finding } from "./analyzer"

const categoryLabels: Record<Finding["category"], string> = {
  typescript: "TypeScript",
  testing: "Testing",
  dependencies: "Dependencies",
  structure: "Structure & Config",
  docs: "Documentation",
  coupling: "Dependency Coupling",
}

export function generateMarkdownReport(
  owner: string,
  repo: string,
  result: AnalysisResult
): string {
  const { score, findings, metadata } = result
  const date = new Date().toISOString().split("T")[0]

  const criticals = findings.filter((f) => f.severity === "critical")
  const warns = findings.filter((f) => f.severity === "warn")
  const infos = findings.filter((f) => f.severity === "info")

  const scoreEmoji = score >= 80 ? "🟢" : score >= 60 ? "🟡" : score >= 40 ? "🟠" : "🔴"

  const byCategory = Object.groupBy(findings, (f) => f.category) as Record<
    Finding["category"],
    Finding[]
  >

  let md = `# CodeLens Analysis: ${owner}/${repo}

**Date:** ${date}
**Score:** ${scoreEmoji} ${score}/100

## Summary

| Metric | Value |
|--------|-------|
| Files scanned | ${metadata.totalFiles} |
| Languages | ${metadata.languages.join(", ") || "Unknown"} |
| TypeScript files | ${metadata.tsFiles} |
| JavaScript files | ${metadata.jsFiles} |
| Test files | ${metadata.testFiles} |
| Critical issues | ${criticals.length} |
| Warnings | ${warns.length} |
| Info | ${infos.length} |

---

`

  for (const [category, catFindings] of Object.entries(byCategory)) {
    if (!catFindings?.length) continue
    md += `## ${categoryLabels[category as Finding["category"]]}\n\n`

    for (const f of catFindings) {
      const icon = f.severity === "critical" ? "🔴" : f.severity === "warn" ? "🟡" : "🔵"
      md += `### ${icon} ${f.title}\n\n`
      md += `**Severity:** ${f.severity}\n\n`
      md += `${f.detail}\n\n`
      md += `**Suggested fix:** ${f.suggestion}\n\n`
      if (f.files?.length) {
        md += `**Affected files:**\n${f.files.map((fp) => `- \`${fp}\``).join("\n")}\n\n`
      }
    }
  }

  md += `---\n*Generated by CodeLens — ${date}*\n`
  return md
}

export function generatePlainSummary(
  owner: string,
  repo: string,
  result: AnalysisResult
): string {
  const { score, findings, metadata } = result
  const criticals = findings.filter((f) => f.severity === "critical")
  const warns = findings.filter((f) => f.severity === "warn")

  const level =
    score >= 80
      ? "well-modernized"
      : score >= 60
      ? "moderately modernized"
      : score >= 40
      ? "in need of modernization"
      : "significantly outdated"

  const topIssues = [...criticals, ...warns]
    .slice(0, 3)
    .map((f) => f.title.toLowerCase())

  const issueText =
    topIssues.length > 0
      ? `The top issues are: ${topIssues.join(", ")}.`
      : "No major issues found."

  return (
    `${owner}/${repo} scored ${score}/100 and is ${level}. ` +
    `CodeLens scanned ${metadata.totalFiles} files across ${metadata.languages.join(", ") || "an unknown stack"}` +
    ` and found ${criticals.length} critical issue${criticals.length !== 1 ? "s" : ""} and ${warns.length} warning${warns.length !== 1 ? "s" : ""}. ` +
    issueText
  )
}
